[tool.black]
target-version = ["py38"]

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "maxcube",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true
