---

name: python-maxcube-api commit validation

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install coveralls
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pre-commit hooks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --hook-stage=push
      - name: Unit Test Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            coverage run setup.py test
            coveralls --service=github
